#!/usr/bin/env bash
set -euo pipefail

force=0
env_file="${OPENSPEC_BUDDY_ENV_FILE:-}"

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --file)
      env_file="$2"
      shift 2
      ;;
    --force)
      force=1
      shift
      ;;
    -h|--help)
      cat <<'EOF'
Usage: init-config.sh [--file .env.openspec-buddy] [--force]

Interactively creates project-local OpenSpec Buddy configuration.
EOF
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n' "$1" >&2
      exit 2
      ;;
  esac
done

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
if [[ -z "$env_file" ]]; then
  env_file="$repo_root/.env.openspec-buddy"
fi

if [[ -f "$env_file" && "$force" -ne 1 ]]; then
  printf '%s already exists. Re-run with --force to replace it.\n' "$env_file" >&2
  exit 2
fi

current_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [[ "$current_branch" == "HEAD" || -z "$current_branch" ]]; then
  current_branch="integration"
fi

remote_url="$(git remote get-url origin 2>/dev/null || true)"
project_owner=""
if [[ "$remote_url" =~ [:\/]([^\/:]+)\/[^\/]+(\.git)?$ ]]; then
  project_owner="${BASH_REMATCH[1]}"
fi

ask() {
  local label="$1"
  local default="$2"
  local value
  if [[ -n "$default" ]]; then
    read -r -p "$label [$default]: " value
    printf '%s' "${value:-$default}"
  else
    read -r -p "$label: " value
    printf '%s' "$value"
  fi
}

format_env_value() {
  local value="$1"
  if [[ "$value" =~ ^[A-Za-z0-9_./:@-]+$ ]]; then
    printf '%s' "$value"
  else
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    printf '"%s"' "$value"
  fi
}

base_branch="$(ask "Buddy base branch" "$current_branch")"
release_branch="$(ask "Release branch" "main")"
project_owner="$(ask "GitHub Project owner" "$project_owner")"
project_number="$(ask "GitHub Project number" "")"
project_title="$(ask "GitHub Project title" "OpenSpec Buddy")"
review_request="$(ask "Auto review request, optional" "")"

for value_name in base_branch release_branch project_owner project_number project_title; do
  if [[ -z "${!value_name}" ]]; then
    printf 'Missing required value: %s\n' "$value_name" >&2
    exit 2
  fi
done

{
  echo "# Generated by OpenSpec Buddy."
  echo "# This file is project-local and should normally stay out of git."
  printf 'OPENSPEC_BUDDY_BASE_BRANCH=%s\n' "$(format_env_value "$base_branch")"
  printf 'OPENSPEC_BUDDY_RELEASE_BRANCH=%s\n' "$(format_env_value "$release_branch")"
  printf 'OPENSPEC_BUDDY_PROJECT_OWNER=%s\n' "$(format_env_value "$project_owner")"
  printf 'OPENSPEC_BUDDY_PROJECT_NUMBER=%s\n' "$(format_env_value "$project_number")"
  printf 'OPENSPEC_BUDDY_PROJECT_TITLE=%s\n' "$(format_env_value "$project_title")"
  if [[ -n "$review_request" ]]; then
    printf 'OPENSPEC_BUDDY_PR_REVIEW_REQUEST=%s\n' "$(format_env_value "$review_request")"
  fi
} >"$env_file"

printf 'wrote: %s\n' "$env_file"
