import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import readline from "node:readline/promises";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const currentFile = fileURLToPath(import.meta.url);
const packageRoot = path.resolve(path.dirname(currentFile), "..");
const skillNames = ["openspec-buddy", "openspec-buddy-auto"];

const configKeys = [
  "OPENSPEC_BUDDY_BASE_BRANCH",
  "OPENSPEC_BUDDY_RELEASE_BRANCH",
  "OPENSPEC_BUDDY_PROJECT_OWNER",
  "OPENSPEC_BUDDY_PROJECT_NUMBER",
  "OPENSPEC_BUDDY_PROJECT_TITLE",
  "OPENSPEC_BUDDY_PR_REVIEW_REQUEST",
];

export function installSkills({ mode, sourceRoot, targetRoot, force = false, dryRun = false }) {
  if (!["copy", "symlink"].includes(mode)) {
    throw new Error(`Unsupported install mode: ${mode}`);
  }

  if (!fs.existsSync(sourceRoot)) {
    throw new Error(`Skill source root does not exist: ${sourceRoot}`);
  }

  if (!dryRun) {
    fs.mkdirSync(targetRoot, { recursive: true });
  }

  const installed = [];
  for (const name of skillNames) {
    const source = path.resolve(sourceRoot, name);
    const destination = path.resolve(targetRoot, name);

    if (!fs.existsSync(path.join(source, "SKILL.md"))) {
      throw new Error(`Missing skill source: ${source}`);
    }

    if (fs.existsSync(destination) || fs.existsSync(path.resolve(destination, ".."))) {
      if (fs.existsSync(destination)) {
        const existing = fs.lstatSync(destination);
        const sameSymlink = existing.isSymbolicLink() && fs.readlinkSync(destination) === source;
        if (sameSymlink && mode === "symlink") {
          installed.push({ name, destination, source, mode, status: "unchanged" });
          continue;
        }
        if (!force) {
          throw new Error(`Destination already exists: ${destination}. Re-run with --force to replace it.`);
        }
        if (!dryRun) {
          fs.rmSync(destination, { recursive: true, force: true });
        }
      }
    }

    if (!dryRun) {
      if (mode === "copy") {
        fs.cpSync(source, destination, { recursive: true, verbatimSymlinks: true });
      } else {
        fs.symlinkSync(source, destination, "dir");
      }
    }

    installed.push({ name, destination, source, mode, status: dryRun ? "planned" : "installed" });
  }

  return installed;
}

export function renderConfigFile(values) {
  const lines = [
    "# Generated by openspec-buddy init.",
    "# This file is project-local and should normally stay out of git.",
  ];

  for (const key of configKeys) {
    const value = values[key];
    if (value === undefined || value === null || value === "") {
      continue;
    }
    lines.push(`${key}=${formatEnvValue(String(value))}`);
  }

  return `${lines.join("\n")}\n`;
}

export function writeConfigFile(filePath, values, { force = false } = {}) {
  const missing = configKeys
    .slice(0, 5)
    .filter((key) => values[key] === undefined || values[key] === null || values[key] === "");
  if (missing.length > 0) {
    throw new Error(`Missing required configuration: ${missing.join(", ")}`);
  }

  if (fs.existsSync(filePath) && !force) {
    throw new Error(`${filePath} already exists. Re-run with --force to replace it.`);
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, renderConfigFile(values), "utf8");
}

export async function main(argv) {
  const [command = "help", ...rest] = argv;
  if (command === "install") {
    return runInstall(rest);
  }
  if (command === "init") {
    return runInit(rest);
  }
  if (command === "doctor") {
    return runDoctor(rest);
  }
  if (command === "help" || command === "--help" || command === "-h") {
    process.stdout.write(helpText());
    return;
  }
  if (command === "version" || command === "--version" || command === "-v") {
    process.stdout.write(`${readPackageVersion()}\n`);
    return;
  }

  throw new Error(`Unknown command: ${command}\n\n${helpText()}`);
}

function runInstall(args) {
  const { flags } = parseArgs(args);
  const targetRoot = resolveTargetRoot(flags);
  const sourceRoot = path.resolve(flags.source ? String(flags.source) : path.join(packageRoot, "skills"));
  const mode = String(flags.mode ?? "copy");
  const force = Boolean(flags.force);
  const dryRun = Boolean(flags["dry-run"]);

  const installed = installSkills({ mode, sourceRoot, targetRoot, force, dryRun });
  for (const entry of installed) {
    process.stdout.write(`${entry.status}: ${entry.name} -> ${entry.destination}\n`);
  }
}

async function runInit(args) {
  const { flags } = parseArgs(args);
  const filePath = path.resolve(String(flags.file ?? ".env.openspec-buddy"));
  const force = Boolean(flags.force);
  const values = await collectConfigValues(flags);

  writeConfigFile(filePath, values, { force });
  process.stdout.write(`wrote: ${filePath}\n`);
}

function runDoctor(args) {
  const { flags } = parseArgs(args);
  const targetRoot = resolveTargetRoot(flags);
  const sourceRoot = path.resolve(flags.source ? String(flags.source) : path.join(packageRoot, "skills"));
  const problems = [];

  for (const name of skillNames) {
    if (!fs.existsSync(path.join(sourceRoot, name, "SKILL.md"))) {
      problems.push(`missing package skill: ${name}`);
    }
    if (!fs.existsSync(path.join(targetRoot, name, "SKILL.md"))) {
      problems.push(`missing installed skill in ${targetRoot}: ${name}`);
    }
  }

  if (problems.length > 0) {
    throw new Error(`OpenSpec Buddy doctor found problems:\n- ${problems.join("\n- ")}`);
  }
  process.stdout.write(`OpenSpec Buddy skills are installed in ${targetRoot}\n`);
}

async function collectConfigValues(flags) {
  const defaults = {
    OPENSPEC_BUDDY_BASE_BRANCH: String(flags["base-branch"] ?? currentGitBranch() ?? "integration"),
    OPENSPEC_BUDDY_RELEASE_BRANCH: String(flags["release-branch"] ?? "main"),
    OPENSPEC_BUDDY_PROJECT_OWNER: String(flags["project-owner"] ?? guessGitHubOwner() ?? ""),
    OPENSPEC_BUDDY_PROJECT_NUMBER: String(flags["project-number"] ?? ""),
    OPENSPEC_BUDDY_PROJECT_TITLE: String(flags["project-title"] ?? "OpenSpec Buddy"),
    OPENSPEC_BUDDY_PR_REVIEW_REQUEST: String(flags["review-request"] ?? flags["pr-review-request"] ?? ""),
  };

  const missingRequired = configKeys.slice(0, 5).filter((key) => defaults[key] === "");
  if (missingRequired.length === 0 && (flags.yes || !process.stdin.isTTY)) {
    return defaults;
  }
  if (!process.stdin.isTTY) {
    throw new Error(`Missing required configuration in non-interactive mode: ${missingRequired.join(", ")}`);
  }

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
  try {
    return {
      OPENSPEC_BUDDY_BASE_BRANCH: await ask(rl, "Buddy base branch", defaults.OPENSPEC_BUDDY_BASE_BRANCH),
      OPENSPEC_BUDDY_RELEASE_BRANCH: await ask(rl, "Release branch", defaults.OPENSPEC_BUDDY_RELEASE_BRANCH),
      OPENSPEC_BUDDY_PROJECT_OWNER: await ask(rl, "GitHub Project owner", defaults.OPENSPEC_BUDDY_PROJECT_OWNER),
      OPENSPEC_BUDDY_PROJECT_NUMBER: await ask(rl, "GitHub Project number", defaults.OPENSPEC_BUDDY_PROJECT_NUMBER),
      OPENSPEC_BUDDY_PROJECT_TITLE: await ask(rl, "GitHub Project title", defaults.OPENSPEC_BUDDY_PROJECT_TITLE),
      OPENSPEC_BUDDY_PR_REVIEW_REQUEST: await ask(rl, "Auto review request, optional", defaults.OPENSPEC_BUDDY_PR_REVIEW_REQUEST),
    };
  } finally {
    rl.close();
  }
}

async function ask(rl, label, defaultValue) {
  const suffix = defaultValue ? ` [${defaultValue}]` : "";
  const answer = await rl.question(`${label}${suffix}: `);
  return answer.trim() || defaultValue;
}

function resolveTargetRoot(flags) {
  if (flags.root) {
    return path.resolve(String(flags.root));
  }

  const target = String(flags.target ?? "agents");
  const home = os.homedir();
  if (target === "agents") {
    return path.join(home, ".agents", "skills");
  }
  if (target === "codex") {
    return path.join(process.env.CODEX_HOME ?? path.join(home, ".codex"), "skills");
  }
  if (target === "project") {
    return path.join(process.cwd(), ".agents", "skills");
  }

  throw new Error(`Unsupported target: ${target}. Use agents, codex, project, or --root.`);
}

function parseArgs(args) {
  const flags = {};
  const positionals = [];
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (!arg.startsWith("--")) {
      positionals.push(arg);
      continue;
    }

    const raw = arg.slice(2);
    if (raw.startsWith("no-")) {
      flags[raw.slice(3)] = false;
      continue;
    }

    const equals = raw.indexOf("=");
    if (equals !== -1) {
      flags[raw.slice(0, equals)] = raw.slice(equals + 1);
      continue;
    }

    const next = args[index + 1];
    if (next && !next.startsWith("--")) {
      flags[raw] = next;
      index += 1;
    } else {
      flags[raw] = true;
    }
  }
  return { flags, positionals };
}

function formatEnvValue(value) {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value;
  }
  return JSON.stringify(value);
}

function currentGitBranch() {
  try {
    const output = execFileSync("git", ["rev-parse", "--abbrev-ref", "HEAD"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return output && output !== "HEAD" ? output : null;
  } catch {
    return null;
  }
}

function guessGitHubOwner() {
  try {
    const remote = execFileSync("git", ["remote", "get-url", "origin"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    const match = remote.match(/[:/]([^/:]+)\/[^/]+(?:\.git)?$/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

function readPackageVersion() {
  const text = fs.readFileSync(path.join(packageRoot, "package.json"), "utf8");
  return JSON.parse(text).version;
}

function helpText() {
  return `OpenSpec Buddy skill distribution

Usage:
  openspec-buddy install [--target agents|codex|project] [--mode copy|symlink] [--force]
  openspec-buddy init [--file .env.openspec-buddy] [--force]
  openspec-buddy doctor [--target agents|codex|project]
  openspec-buddy version

Install targets:
  agents   $HOME/.agents/skills
  codex    $CODEX_HOME/skills, or $HOME/.codex/skills
  project  ./.agents/skills in the current project

Examples:
  openspec-buddy install --target agents --force
  openspec-buddy install --target project --mode copy
  openspec-buddy init
`;
}
